server:
  port: 8080

spring:
  datasource:
    username: root
    password: Stepa24!*
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    #  show-sql: true
    open-in-view: true
  # logs
  logging:
    level:
      org.hibernate.SQL: info


indexing-settings:
  sites:
    - url: http://www.playback.ru
      name: PlayBack.Ru
    - url: http://radiomv.ru
      name: Rariomv.ru
    - url: https://www.dimonvideo.ru
      name: DimonVideo